import pygame


WINDOW_HEIGHT = 480
WINDOW_WIDHT = 720
FULLSCREEN = True

FRAME_TIME = 20


TILE_SIZE = 50
WINDOW_DIMENSIONS = (WINDOW_WIDHT, WINDOW_HEIGHT)
PLAYER_SPEED = 8


#game start
GAMESTART_COFFEE_ITEMS = 0
GAMESTART_JAMMER_ITEMS = 0
GAMESTART_DONUT_ITEMS = 0
GAMESTART_COIN_ITEMS = 0

#controls
PLAYER_MOVE_UP = pygame.K_w
PLAYER_MOVE_DOWN = pygame.K_s
PLAYER_MOVE_LEFT = pygame.K_a
PLAYER_MOVE_RIGHT = pygame.K_d
PLAYER_INTERACT = pygame.K_e
PLAYER_RESET = pygame.K_r


HOTKEY_1 = pygame.K_1
HOTKEY_2 = pygame.K_2
HOTKEY_3 = pygame.K_3
HOTKEY_4 = pygame.K_4

#TODO: This maybe in a data container for controls? ??? 

'''
This are the chances of the items. Therefore the sum of this has to be 1!
Currently (31/03/2021 - 20:53) the likeliness of drops is as follows:
coffee>donut>coin>jammer
'''
ITEM_COIN_CHANCE = 0.2
ITEM_DONUT_CHANCE = 0.3
ITEM_COFFEE_CHANCE = 0.4
ITEM_JAMMER_CHANCE = 0.1

ITEM_COIN_DETECTION_RADIUS = 300
ITEM_COIN_RENDER_DURATION = 0.6

ITEM_DONUT_DURATION = 5

ITEM_JAMMER_DURATION = 5    
ITEM_JAMMER_RAY_LENGTH = 100

ITEM_COFFEE_DURATION = 5
ITEM_COFFEE_SPEED_BOOST = 1.5

# enemy constants
GUARD_SIGHT_LENGTH = 200
GUARD_WAIT_TIME = 0.8

DEBUG_DRAW_COLLISION = False

# Cut Scenes
SKIP_INTRO = True
SKIP_DIALOGS = False

# Audio
DEFAULT_MUSIC_VOLUME = 0.3
DEFAULT_AUDIO_VOLUME = 0.3